/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import javax.swing.ImageIcon;

/**
 *
 * @author Vanness
 */
public class LoginPage1 extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        loginPanel = new javax.swing.JPanel();
        LeCarsLabel = new javax.swing.JLabel();
        SalesLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        toRegisterTabButton = new javax.swing.JLabel();
        regPanel = new javax.swing.JPanel();
        newUserRegLabel = new javax.swing.JLabel();
        regUsernameLabel = new javax.swing.JLabel();
        regUsernameField = new javax.swing.JTextField();
        regPasswordLabel = new javax.swing.JLabel();
        regPasswordField = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        toLoginTabButton = new javax.swing.JLabel();
        regReEnterPasswordLabel = new javax.swing.JLabel();
        regReEnterPasswordField = new javax.swing.JPasswordField();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Username :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(0, 204, 204));
        jTabbedPane1.setForeground(new java.awt.Color(172, 218, 182));
        jTabbedPane1.setOpaque(true);

        loginPanel.setBackground(new java.awt.Color(172, 218, 182));
        loginPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LeCarsLabel.setFont(new java.awt.Font("Source Sans Pro Black", 0, 48)); // NOI18N
        LeCarsLabel.setForeground(new java.awt.Color(51, 51, 51));
        LeCarsLabel.setText("LeCars");

        SalesLabel.setFont(new java.awt.Font("Source Sans Pro ExtraLight", 0, 24)); // NOI18N
        SalesLabel.setForeground(new java.awt.Color(0, 51, 51));
        SalesLabel.setText("Sales Management System");

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        usernameLabel.setText("Username :");

        usernameTextField.setBackground(new java.awt.Color(153, 255, 204));
        usernameTextField.setForeground(new java.awt.Color(0, 0, 0));
        usernameTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 0, 0));
        passwordLabel.setText("Password : ");

        passwordField.setBackground(new java.awt.Color(153, 255, 204));
        passwordField.setForeground(new java.awt.Color(0, 0, 0));
        passwordField.setText("jPasswordField1");
        passwordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(255, 102, 102));
        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(0, 0, 0));
        loginButton.setText("Login");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("No account? Register");

        toRegisterTabButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        toRegisterTabButton.setForeground(new java.awt.Color(0, 0, 255));
        toRegisterTabButton.setText("here");
        toRegisterTabButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toRegisterTabButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toRegisterTabButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordLabel)
                    .addComponent(usernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameTextField)
                            .addComponent(passwordField))
                        .addGap(55, 55, 55))))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toRegisterTabButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SalesLabel)
                    .addComponent(LeCarsLabel))
                .addGap(0, 117, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(LeCarsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SalesLabel)
                .addGap(65, 65, 65)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(loginButton)
                .addGap(58, 58, 58)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(toRegisterTabButton))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", loginPanel);

        regPanel.setBackground(new java.awt.Color(172, 218, 182));
        regPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        newUserRegLabel.setFont(new java.awt.Font("Source Sans Pro Black", 0, 36)); // NOI18N
        newUserRegLabel.setForeground(new java.awt.Color(51, 51, 51));
        newUserRegLabel.setText("New User Registration");

        regUsernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        regUsernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        regUsernameLabel.setText("Username :");

        regUsernameField.setBackground(new java.awt.Color(153, 255, 204));
        regUsernameField.setForeground(new java.awt.Color(0, 0, 0));
        regUsernameField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regUsernameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        regUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUsernameFieldActionPerformed(evt);
            }
        });

        regPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        regPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        regPasswordLabel.setText("Password : ");

        regPasswordField.setBackground(new java.awt.Color(153, 255, 204));
        regPasswordField.setForeground(new java.awt.Color(0, 0, 0));
        regPasswordField.setText("jPasswordField1");
        regPasswordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPasswordFieldActionPerformed(evt);
            }
        });

        registerButton.setBackground(new java.awt.Color(255, 102, 102));
        registerButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(0, 0, 0));
        registerButton.setText("Register");
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Already have an account? Click");

        toLoginTabButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        toLoginTabButton.setForeground(new java.awt.Color(0, 0, 255));
        toLoginTabButton.setText("here");
        toLoginTabButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toLoginTabButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toLoginTabButtonMouseClicked(evt);
            }
        });

        regReEnterPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        regReEnterPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        regReEnterPasswordLabel.setText("Re-enter Password : ");

        regReEnterPasswordField.setBackground(new java.awt.Color(153, 255, 204));
        regReEnterPasswordField.setForeground(new java.awt.Color(0, 0, 0));
        regReEnterPasswordField.setText("jPasswordField1");
        regReEnterPasswordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regReEnterPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regReEnterPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout regPanelLayout = new javax.swing.GroupLayout(regPanel);
        regPanel.setLayout(regPanelLayout);
        regPanelLayout.setHorizontalGroup(
            regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regPanelLayout.createSequentialGroup()
                .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(regPanelLayout.createSequentialGroup()
                        .addContainerGap(52, Short.MAX_VALUE)
                        .addComponent(newUserRegLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, regPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(regUsernameLabel)
                            .addComponent(regPasswordLabel)
                            .addComponent(regReEnterPasswordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(regPanelLayout.createSequentialGroup()
                                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(regPasswordField)
                            .addComponent(regUsernameField)
                            .addComponent(regReEnterPasswordField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, regPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toLoginTabButton)))
                .addGap(47, 47, 47))
        );
        regPanelLayout.setVerticalGroup(
            regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(newUserRegLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regUsernameLabel)
                    .addComponent(regUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regPasswordLabel)
                    .addComponent(regPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regReEnterPasswordLabel)
                    .addComponent(regReEnterPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(registerButton)
                .addGap(50, 50, 50)
                .addGroup(regPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(toLoginTabButton))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", regPanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 470, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void toRegisterTabButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toRegisterTabButtonMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_toRegisterTabButtonMouseClicked

    private void regUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regUsernameFieldActionPerformed

    private void regPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regPasswordFieldActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonActionPerformed

    private void toLoginTabButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toLoginTabButtonMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_toLoginTabButtonMouseClicked

    private void regReEnterPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regReEnterPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regReEnterPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImageIcon icon = new ImageIcon("C:\\Users\\Vanness\\OneDrive\\Documents\\NetBeansProjects\\assignment\\AssignmentTrial\\src\\Code\\chibicar.jpg");
                LoginPage1 d = new LoginPage1();
                d.setIconImage(icon.getImage());
                d.setTitle("LeCars Sales Management System");
                d.setSize(470,525);
                d.setResizable(false);
                d.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LeCarsLabel;
    private javax.swing.JLabel SalesLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel newUserRegLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel regPanel;
    private javax.swing.JPasswordField regPasswordField;
    private javax.swing.JLabel regPasswordLabel;
    private javax.swing.JPasswordField regReEnterPasswordField;
    private javax.swing.JLabel regReEnterPasswordLabel;
    private javax.swing.JTextField regUsernameField;
    private javax.swing.JLabel regUsernameLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel toLoginTabButton;
    private javax.swing.JLabel toRegisterTabButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
