/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vanness
 */
public class MHomePage extends javax.swing.JFrame {
    // Initial import customer data
    final String CUSTPATH = "C:\\Users\\Vanness\\Downloads\\assignmentFiles\\cust.csv";
    ArrayList<ArrayList<String>> customer = ImportExport.importCSV(CUSTPATH);
    
    // Initial import sales data
    final String SALESPATH = "C:\\Users\\Vanness\\Downloads\\assignmentFiles\\sales.csv";
    ArrayList<ArrayList<String>> sales = ImportExport.importCSV(SALESPATH);
    
    // Initial import vehicle data
    final String VEHICLEPATH = "C:\\Users\\Vanness\\Downloads\\assignmentFiles\\vehicle.csv";
    ArrayList<ArrayList<String>> vehicle = ImportExport.importCSV(VEHICLEPATH);
    
    // Initial import employee data
    final String EMPLOYEEPATH = "C:\\Users\\Vanness\\Downloads\\assignmentFiles\\employee.csv";
    ArrayList<ArrayList<String>> employee = ImportExport.importCSV(EMPLOYEEPATH);
    
    /**
     * Creates new form MHomePage
     */
    public MHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        tabPane = new javax.swing.JTabbedPane();
        homeTab = new javax.swing.JPanel();
        hello = new javax.swing.JLabel();
        importTab = new javax.swing.JPanel();
        importDataLabel = new javax.swing.JLabel();
        importVehicleButton = new javax.swing.JButton();
        importSalesButton = new javax.swing.JButton();
        importCustButton = new javax.swing.JButton();
        importEmployeeButton = new javax.swing.JButton();
        insertTab = new javax.swing.JPanel();
        insertTabPane = new javax.swing.JTabbedPane();
        insertCustomerPane = new javax.swing.JPanel();
        customerNamePromptLabel = new javax.swing.JLabel();
        customerNamePromptField = new javax.swing.JTextField();
        postcodePromptLabel = new javax.swing.JLabel();
        phoneNoPromptField = new javax.swing.JTextField();
        phoneNoPromptLabel = new javax.swing.JLabel();
        postcodePromptField = new javax.swing.JTextField();
        phoneNoMessageLabel = new javax.swing.JLabel();
        insertCustSuccessLabel = new javax.swing.JLabel();
        postcodeMessageLabel1 = new javax.swing.JLabel();
        addCustButton = new javax.swing.JButton();
        insertSalesPane = new javax.swing.JPanel();
        carPlatePromptLabelS = new javax.swing.JLabel();
        carPlatePromptField = new javax.swing.JTextField();
        customerIDPromptLabel = new javax.swing.JLabel();
        customerIDPromptOption = new javax.swing.JComboBox<>();
        insertSalesSuccessLabel = new javax.swing.JLabel();
        addSalesButton = new javax.swing.JButton();
        insertVehiclePane = new javax.swing.JPanel();
        insertVehiclePane1 = new javax.swing.JPanel();
        carPlatePromptLabelV = new javax.swing.JLabel();
        carModelPromptLabel = new javax.swing.JLabel();
        carPlatePromptFieldV = new javax.swing.JTextField();
        carModelPromptField = new javax.swing.JTextField();
        acPricePromptLabel = new javax.swing.JLabel();
        acPricePromptField = new javax.swing.JTextField();
        carStatusPromptLabel = new javax.swing.JLabel();
        carStatusPromptOption = new javax.swing.JComboBox<>();
        soldPricePromptLabel = new javax.swing.JLabel();
        soldPricePromptField = new javax.swing.JTextField();
        insertVehSuccessLabel = new javax.swing.JLabel();
        addVehButton = new javax.swing.JButton();
        insertEmployeePane = new javax.swing.JPanel();
        eIDPromptLabel = new javax.swing.JLabel();
        eIDPromptOption = new javax.swing.JComboBox<>();
        insertESuccessLabel = new javax.swing.JLabel();
        addEButton = new javax.swing.JButton();
        eNamePromptLabel = new javax.swing.JLabel();
        ePasswordPromptLabel = new javax.swing.JLabel();
        eNamePromptField = new javax.swing.JTextField();
        ePasswordPromptField = new javax.swing.JTextField();
        insertDataPromptLabel = new javax.swing.JLabel();
        viewTab = new javax.swing.JPanel();
        tableOptionsPromptLabel = new javax.swing.JLabel();
        tableOptionsPrompt = new javax.swing.JComboBox<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        TableTabPane = new javax.swing.JTabbedPane();
        customerTablePane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        salesTablePane = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        vehicleTablePane = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        vehicleTable = new javax.swing.JTable();
        employeeTablePane = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        filterButton = new javax.swing.JButton();
        calculatePanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        importButton = new javax.swing.JLabel();
        homeButton = new javax.swing.JLabel();
        insertButton = new javax.swing.JLabel();
        viewButton = new javax.swing.JLabel();
        calculateButton = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(1024, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabPane.setBackground(new java.awt.Color(51, 51, 51));
        tabPane.setForeground(new java.awt.Color(204, 255, 204));
        tabPane.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        homeTab.setBackground(new java.awt.Color(204, 255, 204));
        homeTab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        hello.setFont(new java.awt.Font("Segoe UI", 1, 120)); // NOI18N
        hello.setForeground(new java.awt.Color(0, 0, 0));
        hello.setText("Hello");

        javax.swing.GroupLayout homeTabLayout = new javax.swing.GroupLayout(homeTab);
        homeTab.setLayout(homeTabLayout);
        homeTabLayout.setHorizontalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(hello, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );
        homeTabLayout.setVerticalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(hello, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        tabPane.addTab("homeTab", homeTab);

        importTab.setBackground(new java.awt.Color(204, 255, 204));
        importTab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        importDataLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        importDataLabel.setForeground(new java.awt.Color(0, 0, 0));
        importDataLabel.setText("Import Data Options");

        importVehicleButton.setBackground(new java.awt.Color(153, 255, 153));
        importVehicleButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        importVehicleButton.setForeground(new java.awt.Color(0, 0, 0));
        importVehicleButton.setText("Vehicle");
        importVehicleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        importVehicleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importVehicleButtonMouseClicked(evt);
            }
        });

        importSalesButton.setBackground(new java.awt.Color(255, 153, 255));
        importSalesButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        importSalesButton.setForeground(new java.awt.Color(0, 0, 0));
        importSalesButton.setText("Sales");
        importSalesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        importSalesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importSalesButtonMouseClicked(evt);
            }
        });

        importCustButton.setBackground(new java.awt.Color(153, 153, 255));
        importCustButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        importCustButton.setForeground(new java.awt.Color(0, 0, 0));
        importCustButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        importCustButton.setLabel("Customer");
        importCustButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importCustButtonMouseClicked(evt);
            }
        });

        importEmployeeButton.setBackground(new java.awt.Color(102, 204, 255));
        importEmployeeButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        importEmployeeButton.setForeground(new java.awt.Color(0, 0, 0));
        importEmployeeButton.setText("Employee");
        importEmployeeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        importEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importEmployeeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout importTabLayout = new javax.swing.GroupLayout(importTab);
        importTab.setLayout(importTabLayout);
        importTabLayout.setHorizontalGroup(
            importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importTabLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(importCustButton, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(importVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(98, 98, 98)
                .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(importEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(importSalesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(205, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, importTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(importDataLabel)
                .addGap(272, 272, 272))
        );
        importTabLayout.setVerticalGroup(
            importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importTabLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(importDataLabel)
                .addGap(45, 45, 45)
                .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importSalesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(importCustButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(importTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(importEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(importVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );

        tabPane.addTab("importTab", importTab);

        insertTab.setBackground(new java.awt.Color(204, 255, 204));
        insertTab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        insertTabPane.setBackground(new java.awt.Color(51, 153, 0));
        insertTabPane.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        insertCustomerPane.setBackground(new java.awt.Color(204, 255, 204));

        customerNamePromptLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        customerNamePromptLabel.setForeground(new java.awt.Color(0, 0, 0));
        customerNamePromptLabel.setText("Customer Name :");
        customerNamePromptLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        postcodePromptLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        postcodePromptLabel.setForeground(new java.awt.Color(0, 0, 0));
        postcodePromptLabel.setText("Postcode :");

        phoneNoPromptField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoPromptFieldActionPerformed(evt);
            }
        });

        phoneNoPromptLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        phoneNoPromptLabel.setForeground(new java.awt.Color(0, 0, 0));
        phoneNoPromptLabel.setText("Phone Number :");

        postcodePromptField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postcodePromptFieldActionPerformed(evt);
            }
        });

        phoneNoMessageLabel.setForeground(new java.awt.Color(255, 0, 0));
        phoneNoMessageLabel.setText("Display something if non-digits are entered");

        insertCustSuccessLabel.setForeground(new java.awt.Color(255, 0, 0));
        insertCustSuccessLabel.setText("Display something if successfully added");

        postcodeMessageLabel1.setForeground(new java.awt.Color(255, 0, 0));
        postcodeMessageLabel1.setText("Display something if non-digits are entered");

        addCustButton.setBackground(new java.awt.Color(255, 51, 51));
        addCustButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addCustButton.setText("Add");
        addCustButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout insertCustomerPaneLayout = new javax.swing.GroupLayout(insertCustomerPane);
        insertCustomerPane.setLayout(insertCustomerPaneLayout);
        insertCustomerPaneLayout.setHorizontalGroup(
            insertCustomerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertCustomerPaneLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(insertCustomerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(customerNamePromptLabel)
                    .addComponent(postcodePromptLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(insertCustomerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(postcodeMessageLabel1)
                    .addComponent(customerNamePromptField, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNoPromptField, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postcodePromptField, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNoMessageLabel)
                    .addGroup(insertCustomerPaneLayout.createSequentialGroup()
                        .addComponent(addCustButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(insertCustSuccessLabel)))
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(insertCustomerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(insertCustomerPaneLayout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(phoneNoPromptLabel)
                    .addContainerGap(711, Short.MAX_VALUE)))
        );
        insertCustomerPaneLayout.setVerticalGroup(
            insertCustomerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertCustomerPaneLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(insertCustomerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(customerNamePromptField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNamePromptLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(phoneNoPromptField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phoneNoMessageLabel)
                .addGap(34, 34, 34)
                .addGroup(insertCustomerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(postcodePromptLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(postcodePromptField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(postcodeMessageLabel1)
                .addGap(34, 34, 34)
                .addGroup(insertCustomerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCustButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertCustSuccessLabel))
                .addGap(23, 23, 23))
            .addGroup(insertCustomerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(insertCustomerPaneLayout.createSequentialGroup()
                    .addGap(159, 159, 159)
                    .addComponent(phoneNoPromptLabel)
                    .addContainerGap(226, Short.MAX_VALUE)))
        );

        insertTabPane.addTab("customer", insertCustomerPane);

        insertSalesPane.setBackground(new java.awt.Color(204, 255, 204));
        insertSalesPane.setForeground(new java.awt.Color(0, 0, 0));

        carPlatePromptLabelS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        carPlatePromptLabelS.setForeground(new java.awt.Color(0, 0, 0));
        carPlatePromptLabelS.setText("Car Plate :");

        carPlatePromptField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carPlatePromptFieldActionPerformed(evt);
            }
        });

        customerIDPromptLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        customerIDPromptLabel.setForeground(new java.awt.Color(0, 0, 0));
        customerIDPromptLabel.setText("Customer ID :");

        customerIDPromptOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID1", "ID2", "ID3", "ID4" }));

        insertSalesSuccessLabel.setForeground(new java.awt.Color(255, 0, 0));
        insertSalesSuccessLabel.setText("Display something if successfully added");

        addSalesButton.setBackground(new java.awt.Color(255, 51, 51));
        addSalesButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addSalesButton.setText("Add");

        javax.swing.GroupLayout insertSalesPaneLayout = new javax.swing.GroupLayout(insertSalesPane);
        insertSalesPane.setLayout(insertSalesPaneLayout);
        insertSalesPaneLayout.setHorizontalGroup(
            insertSalesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertSalesPaneLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(insertSalesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(customerIDPromptLabel)
                    .addComponent(carPlatePromptLabelS))
                .addGap(18, 18, 18)
                .addGroup(insertSalesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertSalesSuccessLabel)
                    .addComponent(addSalesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(insertSalesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(carPlatePromptField, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                        .addComponent(customerIDPromptOption, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        insertSalesPaneLayout.setVerticalGroup(
            insertSalesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertSalesPaneLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(insertSalesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carPlatePromptField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carPlatePromptLabelS))
                .addGap(56, 56, 56)
                .addGroup(insertSalesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDPromptLabel)
                    .addComponent(customerIDPromptOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(addSalesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(insertSalesSuccessLabel)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        insertTabPane.addTab("sales", insertSalesPane);

        insertVehiclePane.setBackground(new java.awt.Color(204, 255, 204));

        insertVehiclePane1.setBackground(new java.awt.Color(204, 255, 204));

        carPlatePromptLabelV.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        carPlatePromptLabelV.setForeground(new java.awt.Color(0, 0, 0));
        carPlatePromptLabelV.setText("Car Plate :");

        carModelPromptLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        carModelPromptLabel.setForeground(new java.awt.Color(0, 0, 0));
        carModelPromptLabel.setText("Car Model :");

        acPricePromptLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        acPricePromptLabel.setForeground(new java.awt.Color(0, 0, 0));
        acPricePromptLabel.setText("Acquired Price :");

        acPricePromptField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acPricePromptFieldActionPerformed(evt);
            }
        });

        carStatusPromptLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        carStatusPromptLabel.setForeground(new java.awt.Color(0, 0, 0));
        carStatusPromptLabel.setText("Car Status :");

        carStatusPromptOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        soldPricePromptLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        soldPricePromptLabel.setForeground(new java.awt.Color(0, 0, 0));
        soldPricePromptLabel.setText("Sold Price :");

        soldPricePromptField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soldPricePromptFieldActionPerformed(evt);
            }
        });

        insertVehSuccessLabel.setForeground(new java.awt.Color(255, 0, 0));
        insertVehSuccessLabel.setText("Display something if successfully added");

        addVehButton.setBackground(new java.awt.Color(255, 51, 51));
        addVehButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addVehButton.setText("Add");

        javax.swing.GroupLayout insertVehiclePane1Layout = new javax.swing.GroupLayout(insertVehiclePane1);
        insertVehiclePane1.setLayout(insertVehiclePane1Layout);
        insertVehiclePane1Layout.setHorizontalGroup(
            insertVehiclePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertVehiclePane1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(insertVehiclePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(soldPricePromptLabel)
                    .addComponent(carStatusPromptLabel)
                    .addComponent(acPricePromptLabel)
                    .addComponent(carPlatePromptLabelV)
                    .addComponent(carModelPromptLabel))
                .addGap(18, 18, 18)
                .addGroup(insertVehiclePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, insertVehiclePane1Layout.createSequentialGroup()
                        .addComponent(addVehButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(insertVehSuccessLabel))
                    .addGroup(insertVehiclePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(carPlatePromptFieldV, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                        .addComponent(carModelPromptField)
                        .addComponent(acPricePromptField)
                        .addComponent(soldPricePromptField)
                        .addComponent(carStatusPromptOption, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        insertVehiclePane1Layout.setVerticalGroup(
            insertVehiclePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertVehiclePane1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(insertVehiclePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carPlatePromptLabelV)
                    .addComponent(carPlatePromptFieldV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(insertVehiclePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carModelPromptLabel)
                    .addComponent(carModelPromptField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(insertVehiclePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(acPricePromptLabel)
                    .addComponent(acPricePromptField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(insertVehiclePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carStatusPromptLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carStatusPromptOption))
                .addGroup(insertVehiclePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertVehiclePane1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(soldPricePromptLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(insertVehiclePane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(soldPricePromptField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(insertVehiclePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertVehSuccessLabel)
                    .addComponent(addVehButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout insertVehiclePaneLayout = new javax.swing.GroupLayout(insertVehiclePane);
        insertVehiclePane.setLayout(insertVehiclePaneLayout);
        insertVehiclePaneLayout.setHorizontalGroup(
            insertVehiclePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertVehiclePaneLayout.createSequentialGroup()
                .addComponent(insertVehiclePane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        insertVehiclePaneLayout.setVerticalGroup(
            insertVehiclePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertVehiclePaneLayout.createSequentialGroup()
                .addComponent(insertVehiclePane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        insertTabPane.addTab("vehicle", insertVehiclePane);

        insertEmployeePane.setBackground(new java.awt.Color(204, 255, 204));

        eIDPromptLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        eIDPromptLabel.setForeground(new java.awt.Color(0, 0, 0));
        eIDPromptLabel.setText("Employee Status :");

        eIDPromptOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        insertESuccessLabel.setForeground(new java.awt.Color(255, 0, 0));
        insertESuccessLabel.setText("Display something if successfully added");

        addEButton.setBackground(new java.awt.Color(255, 51, 51));
        addEButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addEButton.setText("Add");

        eNamePromptLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        eNamePromptLabel.setForeground(new java.awt.Color(0, 0, 0));
        eNamePromptLabel.setText("Employee Name :");

        ePasswordPromptLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ePasswordPromptLabel.setForeground(new java.awt.Color(0, 0, 0));
        ePasswordPromptLabel.setText("Password :");

        eNamePromptField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNamePromptFieldActionPerformed(evt);
            }
        });

        ePasswordPromptField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ePasswordPromptFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertEmployeePaneLayout = new javax.swing.GroupLayout(insertEmployeePane);
        insertEmployeePane.setLayout(insertEmployeePaneLayout);
        insertEmployeePaneLayout.setHorizontalGroup(
            insertEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertEmployeePaneLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(insertEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ePasswordPromptLabel)
                    .addComponent(eIDPromptLabel)
                    .addComponent(eNamePromptLabel))
                .addGap(18, 18, 18)
                .addGroup(insertEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertEmployeePaneLayout.createSequentialGroup()
                        .addComponent(addEButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(insertESuccessLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(insertEmployeePaneLayout.createSequentialGroup()
                        .addGroup(insertEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eNamePromptField, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                            .addComponent(eIDPromptOption, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ePasswordPromptField))
                        .addGap(174, 174, 174))))
        );
        insertEmployeePaneLayout.setVerticalGroup(
            insertEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertEmployeePaneLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(insertEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNamePromptLabel)
                    .addComponent(eNamePromptField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(insertEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eIDPromptLabel)
                    .addComponent(eIDPromptOption))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(insertEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ePasswordPromptLabel)
                    .addComponent(ePasswordPromptField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(insertEmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertESuccessLabel))
                .addGap(71, 71, 71))
        );

        insertTabPane.addTab("employee", insertEmployeePane);

        insertDataPromptLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        insertDataPromptLabel.setForeground(new java.awt.Color(0, 0, 0));
        insertDataPromptLabel.setText("Insert Data Options :");

        insertDataOptions.setBackground(new java.awt.Color(255, 51, 51));
        insertDataOptions.setForeground(new java.awt.Color(255, 255, 255));
        insertDataOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Sales", "Vehicle", "Employee" }));
        insertDataOptions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertDataOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertDataOptionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertTabLayout = new javax.swing.GroupLayout(insertTab);
        insertTab.setLayout(insertTabLayout);
        insertTabLayout.setHorizontalGroup(
            insertTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertTabLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(insertTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(insertTabLayout.createSequentialGroup()
                        .addComponent(insertDataPromptLabel)
                        .addGap(18, 18, 18)
                        .addComponent(insertDataOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        insertTabLayout.setVerticalGroup(
            insertTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertTabLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(insertTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertDataPromptLabel)
                    .addComponent(insertDataOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(insertTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        tabPane.addTab("insertTab", insertTab);

        viewTab.setBackground(new java.awt.Color(204, 255, 204));
        viewTab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tableOptionsPromptLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tableOptionsPromptLabel.setForeground(new java.awt.Color(0, 0, 0));
        tableOptionsPromptLabel.setText("Table Options :");

        tableOptionsPrompt.setBackground(new java.awt.Color(255, 51, 51));
        tableOptionsPrompt.setForeground(new java.awt.Color(255, 255, 255));
        tableOptionsPrompt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Sales", "Vehicle", "Employee" }));
        tableOptionsPrompt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableOptionsPrompt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableOptionsPromptActionPerformed(evt);
            }
        });

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        TableTabPane.setBackground(new java.awt.Color(51, 153, 0));
        TableTabPane.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        customerTablePane.setBackground(new java.awt.Color(102, 255, 204));

        customerTable.setModel(new DefaultTableModel(returnContents(customer),returnHeader(customer))
        );
        customerTable.setEnabled(false);
        jScrollPane3.setViewportView(customerTable);

        javax.swing.GroupLayout customerTablePaneLayout = new javax.swing.GroupLayout(customerTablePane);
        customerTablePane.setLayout(customerTablePaneLayout);
        customerTablePaneLayout.setHorizontalGroup(
            customerTablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        customerTablePaneLayout.setVerticalGroup(
            customerTablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerTablePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableTabPane.addTab("customer", customerTablePane);

        salesTablePane.setBackground(new java.awt.Color(102, 255, 204));
        salesTablePane.setForeground(new java.awt.Color(0, 0, 0));

        salesTable.setModel(new DefaultTableModel(returnContents(sales),returnHeader(sales)));
        salesTable.setEnabled(false);
        jScrollPane4.setViewportView(salesTable);

        javax.swing.GroupLayout salesTablePaneLayout = new javax.swing.GroupLayout(salesTablePane);
        salesTablePane.setLayout(salesTablePaneLayout);
        salesTablePaneLayout.setHorizontalGroup(
            salesTablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        salesTablePaneLayout.setVerticalGroup(
            salesTablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesTablePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableTabPane.addTab("sales", salesTablePane);

        vehicleTablePane.setBackground(new java.awt.Color(102, 255, 204));

        vehicleTable.setModel(new DefaultTableModel(returnContents(vehicle),returnHeader(vehicle)));
        vehicleTable.setEnabled(false);
        jScrollPane5.setViewportView(vehicleTable);

        javax.swing.GroupLayout vehicleTablePaneLayout = new javax.swing.GroupLayout(vehicleTablePane);
        vehicleTablePane.setLayout(vehicleTablePaneLayout);
        vehicleTablePaneLayout.setHorizontalGroup(
            vehicleTablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        vehicleTablePaneLayout.setVerticalGroup(
            vehicleTablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicleTablePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableTabPane.addTab("vehicle", vehicleTablePane);

        employeeTablePane.setBackground(new java.awt.Color(102, 255, 204));

        jScrollPane6.setBackground(new java.awt.Color(102, 255, 204));

        employeeTable.setModel(new DefaultTableModel(returnContents(employee),returnHeader(employee)));
        employeeTable.setEnabled(false);
        jScrollPane6.setViewportView(employeeTable);

        javax.swing.GroupLayout employeeTablePaneLayout = new javax.swing.GroupLayout(employeeTablePane);
        employeeTablePane.setLayout(employeeTablePaneLayout);
        employeeTablePaneLayout.setHorizontalGroup(
            employeeTablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 978, Short.MAX_VALUE)
        );
        employeeTablePaneLayout.setVerticalGroup(
            employeeTablePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeTablePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableTabPane.addTab("employee", employeeTablePane);

        filterButton.setBackground(new java.awt.Color(102, 255, 153));
        filterButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        filterButton.setForeground(new java.awt.Color(0, 0, 0));
        filterButton.setText("Filter");
        filterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filterButton.setToolTipText("Filter");
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewTabLayout = new javax.swing.GroupLayout(viewTab);
        viewTab.setLayout(viewTabLayout);
        viewTabLayout.setHorizontalGroup(
            viewTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewTabLayout.createSequentialGroup()
                .addGroup(viewTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewTabLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(tableOptionsPromptLabel)
                        .addGap(18, 18, 18)
                        .addComponent(tableOptionsPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(599, 599, 599)
                        .addComponent(filterButton))
                    .addGroup(viewTabLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TableTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewTabLayout.setVerticalGroup(
            viewTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewTabLayout.createSequentialGroup()
                .addGroup(viewTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewTabLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(viewTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tableOptionsPromptLabel)
                            .addComponent(tableOptionsPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(filterButton)))
                .addGroup(viewTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewTabLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TableTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        TableTabPane.getAccessibleContext().setAccessibleName("customer");

        tabPane.addTab("viewTab", viewTab);

        calculatePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout calculatePanelLayout = new javax.swing.GroupLayout(calculatePanel);
        calculatePanel.setLayout(calculatePanelLayout);
        calculatePanelLayout.setHorizontalGroup(
            calculatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 937, Short.MAX_VALUE)
        );
        calculatePanelLayout.setVerticalGroup(
            calculatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        tabPane.addTab("calculateTab", calculatePanel);

        getContentPane().add(tabPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1030, 540));

        topPanel.setBackground(new java.awt.Color(102, 255, 204));
        topPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        logoutButton.setBackground(new java.awt.Color(255, 51, 51));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });

        importButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        importButton.setForeground(new java.awt.Color(0, 0, 0));
        importButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        importButton.setText("Import");
        importButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        importButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importButtonMouseClicked(evt);
            }
        });

        homeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(0, 0, 0));
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeButton.setText("Home");
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
        });

        insertButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        insertButton.setForeground(new java.awt.Color(0, 0, 0));
        insertButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        insertButton.setText("Insert");
        insertButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertButtonMouseClicked(evt);
            }
        });

        viewButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewButton.setForeground(new java.awt.Color(0, 0, 0));
        viewButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewButton.setText("View");
        viewButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewButtonMouseClicked(evt);
            }
        });

        calculateButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        calculateButton.setForeground(new java.awt.Color(0, 0, 0));
        calculateButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calculateButton.setText("Calculate");
        calculateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calculateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(importButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calculateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(importButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(logoutButton)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importButtonMouseClicked
        // TODO add your handling code here:
        tabPane.setSelectedIndex(1);
    }//GEN-LAST:event_importButtonMouseClicked

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        // TODO add your handling code here:
        tabPane.setSelectedIndex(0);
    }//GEN-LAST:event_homeButtonMouseClicked

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterButtonActionPerformed

    private void insertButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertButtonMouseClicked
        // TODO add your handling code here:
        tabPane.setSelectedIndex(2);
    }//GEN-LAST:event_insertButtonMouseClicked

    private void viewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewButtonMouseClicked
        // TODO add your handling code here:
        tabPane.setSelectedIndex(3);
    }//GEN-LAST:event_viewButtonMouseClicked

    private void calculateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateButtonMouseClicked
        // TODO add your handling code here:
        tabPane.setSelectedIndex(4);
    }//GEN-LAST:event_calculateButtonMouseClicked

    private void phoneNoPromptFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoPromptFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoPromptFieldActionPerformed

    private void postcodePromptFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postcodePromptFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postcodePromptFieldActionPerformed

    private void acPricePromptFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acPricePromptFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acPricePromptFieldActionPerformed

    private void soldPricePromptFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soldPricePromptFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soldPricePromptFieldActionPerformed

    private void carPlatePromptFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carPlatePromptFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carPlatePromptFieldActionPerformed

    private void eNamePromptFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNamePromptFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eNamePromptFieldActionPerformed

    private void ePasswordPromptFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ePasswordPromptFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ePasswordPromptFieldActionPerformed

    private void insertDataOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertDataOptionsActionPerformed
        // TODO add your handling code here:
        int indexInsert = insertDataOptions.getSelectedIndex();
        if(indexInsert==0)
        insertTabPane.setSelectedIndex(0);
        else if(indexInsert==1)
        insertTabPane.setSelectedIndex(1);
        else if(indexInsert==2)
        insertTabPane.setSelectedIndex(2);
        else
        insertTabPane.setSelectedIndex(3);
    }//GEN-LAST:event_insertDataOptionsActionPerformed

    private void tableOptionsPromptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableOptionsPromptActionPerformed
        // TODO add your handling code here:
        int indexView = tableOptionsPrompt.getSelectedIndex();
        if(indexView==0)
            TableTabPane.setSelectedIndex(0);
        else if(indexView==1)
            TableTabPane.setSelectedIndex(1);
        else if(indexView==2)
            TableTabPane.setSelectedIndex(2);
        else
            TableTabPane.setSelectedIndex(3);
    }//GEN-LAST:event_tableOptionsPromptActionPerformed

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        int logout = JOptionPane.showConfirmDialog(null,"Logging out?", "Warning",JOptionPane.YES_NO_OPTION);
        if(logout==JOptionPane.YES_OPTION){
            ImportExport.ExportCSV(customer,"C:\\Users\\Vanness\\Downloads\\assignmentFiles\\custTest.csv");
            ImportExport.ExportCSV(sales,"C:\\Users\\Vanness\\Downloads\\assignmentFiles\\salesTest.csv");
            ImportExport.ExportCSV(vehicle,"C:\\Users\\Vanness\\Downloads\\assignmentFiles\\vehicleTest.csv");
            ImportExport.ExportCSV(employee,"C:\\Users\\Vanness\\Downloads\\assignmentFiles\\eTest.csv");
            dispose();
        }
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void importCustButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importCustButtonMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("C:\\Users\\Vanness\\Downloads\\assignmentFiles"));// set the directory
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".csv","csv");
        fileChooser.setFileFilter(filter);
        int response = fileChooser.showOpenDialog(null);
        if(response==fileChooser.APPROVE_OPTION){
            ArrayList<ArrayList<String>> temp = ImportExport.importCSV(fileChooser.getSelectedFile().getAbsolutePath());
            String [] tempHeader = returnHeader(temp);
            String [] prevCustHeader = returnHeader(customer);
            boolean compatibility=true;
            // determine if the inserted file has the same column values
            for(int i=0;i<prevCustHeader.length;i++)
                if(!prevCustHeader[i].equalsIgnoreCase(tempHeader[i])){
                    JOptionPane.showMessageDialog(null, "The selected file is not compatible","Warning",JOptionPane.WARNING_MESSAGE);
                    compatibility=false;
                    break;
                }
            // check if the inserted file contains repeated entries
            ArrayList <Integer> avoidAdd = new ArrayList <Integer>();
            for(int i=1;i<temp.size();i++)
                for(int j=0;j<temp.get(i).size();j++){
                    String key = temp.get(i).get(j);
                    for(int m=1;m<customer.size();m++)
                        for(int n=0;n<customer.get(i).size();n++)
                            if(customer.get(m).get(n).equalsIgnoreCase(key))
                                avoidAdd.add(i); 
                }
            if(compatibility){
                customer.addAll(returnContents(temp,avoidAdd));
                JOptionPane.showMessageDialog(null, "File added successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_importCustButtonMouseClicked

    private void importSalesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importSalesButtonMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("C:\\Users\\Vanness\\Downloads\\assignmentFiles"));// set the directory
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".csv","csv");
        fileChooser.setFileFilter(filter);
        int response = fileChooser.showOpenDialog(null);
        if(response==fileChooser.APPROVE_OPTION){
            ArrayList<ArrayList<String>> temp = ImportExport.importCSV(fileChooser.getSelectedFile().getAbsolutePath());
            String [] tempHeader = returnHeader(temp);
            String [] prevSalesHeader = returnHeader(sales);
            boolean compatibility=true;
            // determine if the inserted file has the same column values
            for(int i=0;i<prevSalesHeader.length;i++)
                if(!prevSalesHeader[i].equalsIgnoreCase(tempHeader[i])){
                    JOptionPane.showMessageDialog(null, "The selected file is not compatible","Warning",JOptionPane.WARNING_MESSAGE);
                    compatibility=false;
                    break;
                }
            // check if the inserted file contains repeated entries
            ArrayList <Integer> avoidAdd = new ArrayList <Integer>();
            for(int i=1;i<temp.size();i++)
                for(int j=0;j<temp.get(i).size();j++){
                    String key = temp.get(i).get(j);
                    for(int m=1;m<sales.size();m++)
                        for(int n=0;n<sales.get(i).size();n++)
                            if(sales.get(m).get(n).equalsIgnoreCase(key))
                                avoidAdd.add(i); 
                }
            if(compatibility){
                sales.addAll(returnContents(temp,avoidAdd));
                JOptionPane.showMessageDialog(null, "File added successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_importSalesButtonMouseClicked

    private void importVehicleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importVehicleButtonMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("C:\\Users\\Vanness\\Downloads\\assignmentFiles"));// set the directory
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".csv","csv");
        fileChooser.setFileFilter(filter);
        int response = fileChooser.showOpenDialog(null);
        if(response==fileChooser.APPROVE_OPTION){
            ArrayList<ArrayList<String>> temp = ImportExport.importCSV(fileChooser.getSelectedFile().getAbsolutePath());
            String [] tempHeader = returnHeader(temp);
            String [] prevVehHeader = returnHeader(vehicle);
            boolean compatibility=true;
            // determine if the inserted file has the same column values
            for(int i=0;i<prevVehHeader.length;i++)
                if(!prevVehHeader[i].equalsIgnoreCase(tempHeader[i])){
                    JOptionPane.showMessageDialog(null, "The selected file is not compatible","Warning",JOptionPane.WARNING_MESSAGE);
                    compatibility=false;
                    break;
                }
            // check if the inserted file contains repeated entries
            ArrayList <Integer> avoidAdd = new ArrayList <Integer>();
            for(int i=1;i<temp.size();i++)
                for(int j=0;j<temp.get(i).size();j++){
                    String key = temp.get(i).get(j);
                    for(int m=1;m<vehicle.size();m++)
                        for(int n=0;n<vehicle.get(i).size();n++)
                            if(vehicle.get(m).get(n).equalsIgnoreCase(key))
                                avoidAdd.add(i); 
                }
            if(compatibility){
                vehicle.addAll(returnContents(temp,avoidAdd));
                JOptionPane.showMessageDialog(null, "File added successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_importVehicleButtonMouseClicked

    private void importEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importEmployeeButtonMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("C:\\Users\\Vanness\\Downloads\\assignmentFiles"));// set the directory
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".csv","csv");
        fileChooser.setFileFilter(filter);
        int response = fileChooser.showOpenDialog(null);
        if(response==fileChooser.APPROVE_OPTION){
            ArrayList<ArrayList<String>> temp = ImportExport.importCSV(fileChooser.getSelectedFile().getAbsolutePath());
            String [] tempHeader = returnHeader(temp);
            String [] prevEHeader = returnHeader(employee);
            boolean compatibility=true;
            // determine if the inserted file has the same column values
            for(int i=0;i<prevEHeader.length;i++)
                if(!prevEHeader[i].equalsIgnoreCase(tempHeader[i])){
                    JOptionPane.showMessageDialog(null, "The selected file is not compatible","Warning",JOptionPane.WARNING_MESSAGE);
                    compatibility=false;
                    break;
                }
            // check if the inserted file contains repeated entries
            ArrayList <Integer> avoidAdd = new ArrayList <Integer>();
            for(int i=1;i<temp.size();i++)
                for(int j=0;j<temp.get(i).size();j++){
                    String key = temp.get(i).get(j);
                    for(int m=1;m<employee.size();m++)
                        for(int n=0;n<employee.get(i).size();n++)
                            if(employee.get(m).get(n).equalsIgnoreCase(key))
                                avoidAdd.add(i); 
                }
            if(compatibility){
                employee.addAll(returnContents(temp,avoidAdd));
                JOptionPane.showMessageDialog(null, "File added successfully!","Success",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_importEmployeeButtonMouseClicked

    public static String [] returnHeader (ArrayList<ArrayList<String>> data){
        String [] temp = data.get(0).toArray(new String[data.get(0).size()]);
        return temp;
    }
    public static String [][] returnContents (ArrayList<ArrayList<String>> data){
        String [][] temp = new String [data.size()-1][data.get(0).size()];
        int m=0;
        for(int i=1;i<data.size();i++){
            int n=0;
            for(int j=0;j<data.get(0).size();j++){
                temp[m][n]=data.get(i).get(j);
                n++;
            }
            m++;
        }
        return temp;
    }
    public static ArrayList<ArrayList<String>> returnContents (ArrayList<ArrayList<String>> data,ArrayList<Integer> avoidAdd){
        // this method return contents that are not already present in the previous data
        ArrayList<ArrayList<String>> temp = new ArrayList<ArrayList<String>>();
        for(int i=1;i<data.size();i++){
            boolean skip=false;
            for(int j=0;j<avoidAdd.size();j++)
                if(i==avoidAdd.get(j)){
                    skip=true;
                    break;
                }
            if(!skip)
                temp.add(new ArrayList<String>(data.get(i)));
        }
        return temp;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TableTabPane;
    private javax.swing.JTextField acPricePromptField;
    private javax.swing.JLabel acPricePromptLabel;
    private javax.swing.JButton addCustButton;
    private javax.swing.JButton addEButton;
    private javax.swing.JButton addSalesButton;
    private javax.swing.JButton addVehButton;
    private javax.swing.JLabel calculateButton;
    private javax.swing.JPanel calculatePanel;
    private javax.swing.JTextField carModelPromptField;
    private javax.swing.JLabel carModelPromptLabel;
    private javax.swing.JTextField carPlatePromptField;
    private javax.swing.JTextField carPlatePromptFieldV;
    private javax.swing.JLabel carPlatePromptLabelS;
    private javax.swing.JLabel carPlatePromptLabelV;
    private javax.swing.JLabel carStatusPromptLabel;
    private javax.swing.JComboBox<String> carStatusPromptOption;
    private javax.swing.JLabel customerIDPromptLabel;
    private javax.swing.JComboBox<String> customerIDPromptOption;
    private javax.swing.JTextField customerNamePromptField;
    private javax.swing.JLabel customerNamePromptLabel;
    private javax.swing.JTable customerTable;
    private javax.swing.JPanel customerTablePane;
    private javax.swing.JLabel eIDPromptLabel;
    private javax.swing.JComboBox<String> eIDPromptOption;
    private javax.swing.JTextField eNamePromptField;
    private javax.swing.JLabel eNamePromptLabel;
    private javax.swing.JTextField ePasswordPromptField;
    private javax.swing.JLabel ePasswordPromptLabel;
    private javax.swing.JTable employeeTable;
    private javax.swing.JPanel employeeTablePane;
    private javax.swing.JButton filterButton;
    private javax.swing.JLabel hello;
    private javax.swing.JLabel homeButton;
    private javax.swing.JPanel homeTab;
    private javax.swing.JLabel importButton;
    private javax.swing.JButton importCustButton;
    private javax.swing.JLabel importDataLabel;
    private javax.swing.JButton importEmployeeButton;
    private javax.swing.JButton importSalesButton;
    private javax.swing.JPanel importTab;
    private javax.swing.JButton importVehicleButton;
    private javax.swing.JLabel insertButton;
    private javax.swing.JLabel insertCustSuccessLabel;
    private javax.swing.JPanel insertCustomerPane;
    private final javax.swing.JComboBox<String> insertDataOptions = new javax.swing.JComboBox<>();
    private javax.swing.JLabel insertDataPromptLabel;
    private javax.swing.JLabel insertESuccessLabel;
    private javax.swing.JPanel insertEmployeePane;
    private javax.swing.JPanel insertSalesPane;
    private javax.swing.JLabel insertSalesSuccessLabel;
    private javax.swing.JPanel insertTab;
    private javax.swing.JTabbedPane insertTabPane;
    private javax.swing.JLabel insertVehSuccessLabel;
    private javax.swing.JPanel insertVehiclePane;
    private javax.swing.JPanel insertVehiclePane1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel phoneNoMessageLabel;
    private javax.swing.JTextField phoneNoPromptField;
    private javax.swing.JLabel phoneNoPromptLabel;
    private javax.swing.JLabel postcodeMessageLabel1;
    private javax.swing.JTextField postcodePromptField;
    private javax.swing.JLabel postcodePromptLabel;
    private javax.swing.JTable salesTable;
    private javax.swing.JPanel salesTablePane;
    private javax.swing.JTextField soldPricePromptField;
    private javax.swing.JLabel soldPricePromptLabel;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JComboBox<String> tableOptionsPrompt;
    private javax.swing.JLabel tableOptionsPromptLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTable vehicleTable;
    private javax.swing.JPanel vehicleTablePane;
    private javax.swing.JLabel viewButton;
    private javax.swing.JPanel viewTab;
    // End of variables declaration//GEN-END:variables
}
